openapi: 3.0.0
info:
  title: Notes API
  version: 1.0.0
  description: 노트 CRUD API 명세서

paths:
  /notes:
    post:
      summary: 노트 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - tag
              properties:
                title:
                  type: string
                  example: "노트 제목"
                content:
                  type: string
                  example: "노트 내용"
                tag:
                  type: string
                  example: "공부"
      responses:
        "201":
          description: 생성된 노트 반환
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"
    get:
      summary: 모든 노트 조회
      responses:
        "200":
          description: 노트 목록 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Note"

  /notes/{tag}:
    get:
      summary: 태그별 노트 조회
      parameters:
        - in: path
          name: tag
          required: true
          schema:
            type: string
          description: 노트 태그
      responses:
        "200":
          description: 태그별 노트 목록 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Note"

  /notes/{id}:
    put:
      summary: 노트 수정
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 노트 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tag:
                  type: string
      responses:
        "200":
          description: 수정된 노트 반환
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"
        "404":
          description: 노트 없음
    delete:
      summary: 노트 삭제
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 노트 ID
      responses:
        "204":
          description: 삭제 성공
        "404":
          description: 노트 없음

components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        tag:
          type: string
    NoteResponse:
      type: object
      properties:
        message:
          type: string
        data:
          $ref: "#/components/schemas/Note"
